"""add career hub tables (resumes, job applications)

Revision ID: 0be9e51de870
Revises: 497f8b15ad00
Create Date: 2026-07-06 13:49:56.912894

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0be9e51de870"
down_revision: Union[str, Sequence[str], None] = "497f8b15ad00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("date_applied", sa.Date(), nullable=True),
        sa.Column("ctc", sa.Text(), nullable=True),
        sa.Column("source_link", sa.Text(), nullable=True),
        sa.Column("referral_taken_by", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "applied",
                "interview",
                "offer",
                "rejected",
                "withdrawn",
                name="job_application_status",
            ),
            nullable=False,
        ),
        sa.Column("hr_contact", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "resumes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("version_label", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resumes")
    op.drop_table("job_applications")
    # ### end Alembic commands ###
    sa.Enum(name="job_application_status").drop(op.get_bind(), checkfirst=True)
