"""add user_profile table

Revision ID: 4801046a6287
Revises: 0a4c559c38d1
Create Date: 2026-07-05 02:05:32.906292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4801046a6287'
down_revision: Union[str, Sequence[str], None] = '0a4c559c38d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('wake_time', sa.Text(), nullable=False),
    sa.Column('sleep_time', sa.Text(), nullable=False),
    sa.Column('meal_times', sa.JSON(), nullable=False),
    sa.Column('work_start', sa.Text(), nullable=False),
    sa.Column('work_end', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
