"""add learning hub tables (courses, certifications, revision items)

Revision ID: 497f8b15ad00
Revises: 9113061e8d1f
Create Date: 2026-07-06 12:52:27.921075

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "497f8b15ad00"
down_revision: Union[str, Sequence[str], None] = "9113061e8d1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("issuer", sa.Text(), nullable=True),
        sa.Column("date_received", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("planned", "done", name="certification_status"),
            nullable=False,
        ),
        sa.Column("file_url", sa.Text(), nullable=True),
        sa.Column("file_type", sa.Text(), nullable=True),
        sa.Column("inactivity_nudge_sent", sa.Boolean(), nullable=False),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("planned", "in_progress", "done", name="course_status"),
            nullable=False,
        ),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("roadmap_position", sa.Integer(), nullable=True),
        sa.Column("roadmap_rationale", sa.Text(), nullable=True),
        sa.Column("deadline_reminder_sent", sa.Boolean(), nullable=False),
        sa.Column("inactivity_nudge_sent", sa.Boolean(), nullable=False),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "revision_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("next_review_at", sa.Date(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("revision_items")
    op.drop_table("courses")
    op.drop_table("certifications")
    # ### end Alembic commands ###
    sa.Enum(name="course_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="certification_status").drop(op.get_bind(), checkfirst=True)
