"""add avatar_url to user_profile

Revision ID: 703661314cf3
Revises: e7ae35c0e6fd
Create Date: 2026-07-05 23:41:48.824684

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "703661314cf3"
down_revision: Union[str, Sequence[str], None] = "e7ae35c0e6fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile",
        sa.Column("avatar_url", sa.Text(), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "avatar_url")
    # ### end Alembic commands ###
