"""add planner items table and conversation mode column

Revision ID: 9113061e8d1f
Revises: 703661314cf3
Create Date: 2026-07-06 01:54:07.579998

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9113061e8d1f"
down_revision: Union[str, Sequence[str], None] = "703661314cf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "planner_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("daily", "weekly", "monthly", name="planner_mode"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("hours_needed", sa.Float(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column(
            "status", sa.Enum("pending", "done", name="planner_status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("conversations", sa.Column("mode", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "mode")
    op.drop_table("planner_items")
    # ### end Alembic commands ###
    sa.Enum(name="planner_mode").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="planner_status").drop(op.get_bind(), checkfirst=True)
