"""add resume storage provider metadata

Revision ID: cb5136a6c51b
Revises: 0be9e51de870
Create Date: 2026-07-06 15:25:46.034382

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb5136a6c51b"
down_revision: Union[str, Sequence[str], None] = "0be9e51de870"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resumes",
        sa.Column(
            "storage_provider", sa.Text(), server_default="cloudinary", nullable=False
        ),
    )
    op.add_column("resumes", sa.Column("storage_key", sa.Text(), nullable=True))
    op.add_column(
        "resumes", sa.Column("storage_resource_type", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "storage_resource_type")
    op.drop_column("resumes", "storage_key")
    op.drop_column("resumes", "storage_provider")
    # ### end Alembic commands ###
