"""add just_found status and category to job applications

Revision ID: d4d149250865
Revises: ec766306e7ef
Create Date: 2026-07-06 23:40:12.623913

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4d149250865"
down_revision: Union[str, Sequence[str], None] = "ec766306e7ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_applications", sa.Column("category", sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # autogenerate doesn't diff enum members — added by hand. Positioned
    # first since "just found" is conceptually the stage before "applied".
    op.execute(
        "ALTER TYPE job_application_status ADD VALUE 'just_found' BEFORE 'applied'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_applications", "category")
    # ### end Alembic commands ###
    # Postgres has no DROP VALUE for enums — recreate the type without
    # 'just_found'. Only safe if no row currently uses it (true here since
    # this value is brand new), which the USING cast below would fail
    # loudly on otherwise rather than silently corrupting data.
    op.execute("ALTER TYPE job_application_status RENAME TO job_application_status_old")
    op.execute(
        "CREATE TYPE job_application_status AS ENUM "
        "('applied','interview','offer','rejected','withdrawn')"
    )
    op.execute("ALTER TABLE job_applications ALTER COLUMN status DROP DEFAULT")
    op.execute(
        "ALTER TABLE job_applications ALTER COLUMN status TYPE job_application_status "
        "USING status::text::job_application_status"
    )
    op.execute("ALTER TABLE job_applications ALTER COLUMN status SET DEFAULT 'applied'")
    op.execute("DROP TYPE job_application_status_old")
