"""add certification storage metadata

Revision ID: f170de7831da
Revises: cb5136a6c51b
Create Date: 2026-07-06 15:31:47.765918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f170de7831da'
down_revision: Union[str, Sequence[str], None] = 'cb5136a6c51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certifications', sa.Column('storage_key', sa.Text(), nullable=True))
    op.add_column('certifications', sa.Column('storage_resource_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certifications', 'storage_resource_type')
    op.drop_column('certifications', 'storage_key')
    # ### end Alembic commands ###
