"""add certification credential fields and tags

Revision ID: f54deaff5ae9
Revises: f170de7831da
Create Date: 2026-07-06 15:46:07.474597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54deaff5ae9'
down_revision: Union[str, Sequence[str], None] = 'f170de7831da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certifications', sa.Column('credential_id', sa.Text(), nullable=True))
    op.add_column('certifications', sa.Column('credential_url', sa.Text(), nullable=True))
    op.add_column('certifications', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certifications', 'tags')
    op.drop_column('certifications', 'credential_url')
    op.drop_column('certifications', 'credential_id')
    # ### end Alembic commands ###
